[info]
gist = "Disc burning utility"
category = "Utilities"
name = "CDBurnerXP"

[html]
versioning = "tuple"
blob_re = "<td><a href=\"(?P<url>https://download\\.cdburnerxp\\.se/portable/CDBurnerXP-x64-(?P<ver>.*?)\\.zip)\" onclick=\".*?\">64 bit</a></td>"
url = "https://cdburnerxp.se/download"
