[info]
gist = "Emulates the Nintendo Wii U."
category = "Emulators"
name = "Cemu"

[html]
versioning = "tuple"
blob_re = ".*\"(?P<url>https://cemu\\.info/releases/cemu_(?P<ver>.*?)\\.zip)\".*"
url = "http://cemu.info/"
