[info]
gist = "Emulates the Nintendo 3DS. The 'canary' branch has all the latest features, but might be less stable than 'nightly'."
category = "Emulators"
name = "citra-canary"

[github]
blob_re = "^citra.*windows.*\\.7z$"
user = "citra-emu"
project = "citra-canary"
