[info]
gist = "Emulates the Microsoft Xbox."
category = "Emulators"
name = "Cxbx-Reloaded"

[github]
prerelease = true
blob_re = "^CxbxReloaded-Release-VS2022\\.zip$"
user = "Cxbx-Reloaded"
project = "Cxbx-Reloaded"
