name = "dbeaver"
user = "dbeaver"
project = "dbeaver"
blob_re = "^dbeaver.*win32\\.x86_64.*\\.zip$"
blob_unwanted = []
appdatas = [
    "dbeaver.ini",
]
repo = "github"

[info]
gist = "SQL client"
category = "Developer Tools"
