[info]
gist = "Diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams. Previously known as draw.io"
category = "Developer Tools"
name = "diagrams.net"

[github]
blob_re = "^draw.io-.*-windows-no-installer\\.exe$"
user = "jgraph"
project = "drawio-desktop"
