[info]
gist = "Emulates the Sony PlayStation. Preview build (or development if newer)"
category = "Emulators"
name = "DuckStation Preview"

[github]
prerelease = true
blob_re = "^duckstation-windows-x64-release\\.zip$"
user = "stenzek"
project = "duckstation"
