[info]
name = "DuckStation"
category = "Emulators"
gist = "Emulates the Sony PlayStation. Development build"

[github]
blob_re = "^duckstation-windows-x64-release\\.zip$"
user = "stenzek"
project = "duckstation"
