[info]
gist = "Emulates the Sony PlayStation. Development build"
category = "Emulators"
name = "DuckStation"

[github]
blob_re = "^duckstation-windows-x64-release\\.zip$"
user = "stenzek"
project = "duckstation"
