[info]
gist = "FLOSS YouTube frontend with a focus on privacy."
category = "Audio & Video"
name = "FreeTube"

[github]
prerelease = true
blob_re = "^freetube-.*?-win-x64-portable\\.zip$"
user = "FreeTubeApp"
project = "FreeTube"
