[info]
gist = "File manager"
category = "Utilities"
name = "FreeCommander XE"

[html]
versioning = "integer"
ver_scheme_re = "<span style=\".*?\">FreeCommander XE 2022 Build (.*?) portable ZIP</span>"
url = "https://freecommander.com/en/downloads-portable/"
blob_permalink = "https://freecommander.com/downloads/FreeCommanderXE-32-public_portable.zip"
