[info]
gist = "Audio/video converter built on top of ffmpeg"
category = "Audio & Video"
name = "HandBrake"

[github]
blob_re = "^HandBrake-.*-x86_64-Win_GUI\\.zip$"
user = "HandBrake"
project = "HandBrake"
