[info]
gist = "Hex editor"
category = "Developer Tools"
name = "HxD"

[html]
versioning = "tuple"
ver_scheme_re = "[\\S\\s]*<h2>HxD</h2>[\\S\\s]*<span style=\\\"float: left;\\\">(.*?) .*?</span>[\\S\\s]*"
url = "https://mh-nexus.de/en/programs.php"
blob_permalink = "https://mh-nexus.de/downloads/HxDPortableSetup.zip"

[local]
installer = "innoextract"
delete = [
    "HxD\\.exe",
]
