[info]
name = "HxD"
category = "Developer Tools"
gist = "Hex editor"

[html]
url = "https://mh-nexus.de/en/programs.php"
versioning = "tuple"
blob_permalink = "https://mh-nexus.de/downloads/HxDPortableSetup.zip"
blob_permalink_re = "[\\S\\s]*<h2>HxD</h2>[\\S\\s]*<span style=\\\"float: left;\\\">(.*?) .*?</span>[\\S\\s]*"

[local]
installer = "innoextract"
delete = [
    "HxD\\.exe",
]
