[info]
name = "Joplin"
category = "Utilities"
gist = "an open source note taking and to-do application with synchronisation capabilities"

[github]
blob_re = "^JoplinPortable\\.exe$"
user = "laurent22"
project = "Joplin"

