[info]
name = "Joplin"
category = "Utilities"
gist = "A free and open source note-taking and task management app with synchronization capabilities"

[github]
blob_re = "^JoplinPortable\\.exe$"
user = "laurent22"
project = "Joplin"
