[info]
gist = "Non-linear video editor"
category = "Audio & Video"
name = "Kdenlive"

[html]
versioning = "tuple"
blob_re = "(?P<url>https://download\\.kde\\.org/stable/kdenlive/.*?/windows/kdenlive-(?P<ver>.*?)_standalone\\.exe)"
url = "https://kdenlive.org/en/download/"

[local]
installer = "sfx"
