[info]
name = "Kdenlive"
category = "Audio & Video"
gist = "Non-linear video editor"

[html]
url = "https://kdenlive.org/en/download/"
versioning = "tuple"
blob_re = "(?P<url>https://download\\.kde\\.org/stable/kdenlive/.*?/windows/kdenlive-(?P<ver>.*?)_standalone\\.exe)"

[local]
installer = "sfx"
