[info]
gist = "Frontend for the media libraries of German public broadcasters like ARD and ZDF"
category = "Audio & Video"
name = "MediathekView"

[github]
blob_re = "^MediathekView-.*?-win32\\.zip$"
user = "mediathekview"
project = "MediathekView"
