[info]
gist = "Emulates the Nintendo Game Boy, Game Boy Color and Game Boy Advance."
category = "Emulators"
name = "mGBA"

[github]
blob_re = "^mGBA.*win64.*\\.7z$"
user = "mgba-emu"
project = "mgba"
