[info]
gist = "Free and open-source video and audio player (active fork by clsid2). Very high performance"
category = "Audio & Video"
name = "Media Player Classic - Home Cinema"

[github]
blob_re = "^MPC-HC\\..*?\\.x64\\.zip$"
user = "clsid2"
project = "mpc-hc"
