[info]
name = "notepad2"
category = "Utilities"
gist = "a light-weight Scintilla-based text editor for Windows with syntax highlighting, code folding, auto-completion and API list for about 80 programming languages/documents"

[github]
blob_re = "^Notepad2_en_AVX2_.*.zip$"
user = "zufuliu"
project = "notepad2"

[local]
delete = [ "Notepad2.ini", ]
