[info]
name = "nvidiaProfileInspector"
category = "Gaming"
gist = "3rd-party Nvidia driver configuration frontend"

[github]
blob_re = "^nvidiaProfileInspector\\.zip$"
user = "Orbmu2k"
project = "nvidiaProfileInspector"
