[info]
gist = "3rd-party Nvidia driver configuration frontend"
category = "Gaming"
name = "nvidiaProfileInspector"

[github]
blob_re = "^nvidiaProfileInspector\\.zip$"
user = "Orbmu2k"
project = "nvidiaProfileInspector"
