name = "paint.net"
user = "paintdotnet"
project = "release"
blob_re = "^paint\\.net\\..*?portable\\.x64\\.zip$"
blob_unwanted = []
appdatas = [
    "PaintDotNet.AppSettings.json",
]
repo = "github"

[info]
gist = "Freeware image editor originally conceived as an alternative to Microsoft Paint."
category = "Utilities"
