[info]
gist = "Emulates the Sony PlayStation 2. AVX2 Development builds"
category = "Emulators"
name = "PCSX2"

[github]
prerelease = true
blob_re = "^pcsx2-.*-windows-64bit-AVX2.7z$"
user = "PCSX2"
project = "pcsx2"

[local]
appdata = [
    "portable.ini",
]
