[info]
name = "PCSX2"
category = "Emulators"
gist = "Emulates the Sony PlayStation 2. Qt-AVX2 Development builds"

[github]
blob_re = "^pcsx2-.*-windows-64bit-AVX2-Qt\\.7z$"
user = "PCSX2"
project = "pcsx2"
prerelease = true

[local]
appdata = [
    "portable.ini",
]
