[info]
name = "PCSX2-SSE4"
category = "Emulators"
gist = "Emulates the Sony PlayStation 2. Qt-SSE4 Development builds (use if your CPU has no AVX2)"

[github]
blob_re = "^pcsx2-.*-windows-64bit-SSE4-Qt\\.7z$"
user = "PCSX2"
project = "pcsx2"
prerelease = true

[local]
appdata = [
    "portable.ini",
]
