[info]
gist = "Emulates the Sony PlayStation Portable. Development builds from Git via Orphis."
category = "Emulators"
name = "PPSSPP Development"

[html]
versioning = "tuple"
blob_re = ".*(?P<url>/ppsspp/index\\.php\\?m=dl&amp;rev=v*(?P<ver>.*?)&amp;platform=windows-amd64).*"
url = "https://buildbot.orphis.net/ppsspp"
