[info]
gist = "Emulates the Nintendo 64. The 'Development' branch has all the latest features, but might be less stable."
category = "Emulators"
name = "Project64-Development"

[html]
versioning = "integer"
blob_re = "\"(?P<url>/file/setup-project64-.*-(?P<ver>.*?)-.*?/)\""
url = "https://www.pj64-emu.com/nightly-builds"

[local]
installer = "innoextract"
