[info]
gist = "Clean directory structures using rulesets"
category = "Utilities"
name = "Remove Empty Directories"

[github]
blob_re = "^red.*portable.*\\.zip$"
user = "hxseven"
project = "Remove-Empty-Directories"
