[info]
gist = "Frontend for emulators, game engines and media players."
category = "Emulators"
name = "RetroArch"

[html]
versioning = "tuple"
blob_re = ".*<a href=\"(?P<url>https://buildbot\\.libretro\\.com/stable/(?P<ver>.*?)/windows/x86_64/RetroArch\\.7z)\".*"
url = "https://retroarch.com/index.php?page=platforms"
