[info]
gist = "Emulates the Sony PlayStation 3."
category = "Emulators"
name = "RPCS3"

[html]
versioning = "id"
ver_scheme_spec = 1
ver_scheme_re = "<span>Build <span class='version-buildversion'>(.*?)</span></span>"
url = "https://rpcs3.net/download"
blob_permalink = "https://rpcs3.net/latest-windows"
