name = "Rufus"
user = "pbatard"
project = "rufus"
blob_re = "^rufus-.*p\\.exe$"
blob_unwanted = []
appdatas = []
repo = "github"

[info]
gist = "Create bootable USB flash drives"
category = "Utilities"
