name = "Ryujinx"
user = "Ryujinx"
project = "release-channel-master"
blob_re = "ryujinx-[0-9\\.]*-win_x64\\.zip$"
blob_unwanted = []
appdatas = []
repo = "github"

[info]
gist = "Emulates the Nintendo Switch."
category = "Emulators"
