[info]
name = "Steam Rom Manager"
category = "Gaming"
gist = "Add roms to Steam as shortcuts with library images"

[github]
blob_re = "^Steam-ROM-Manager-portable.*\\.exe$"
user = "doZennn"
project = "steam-rom-manager"
