[info]
name = "Steamless"
category = "Utilities"
gist = "Steamless is a DRM remover and unpacker for Steam games"

[github]
blob_re = "^Steamless\\.v?.*?\\.-\\.by\\.atom0s\\.zip$"
user = "atom0s"
project = "Steamless"
