[info]
gist = "Add roms to Steam as shortcuts with library images"
category = "Gaming"
name = "Steam Rom Manager"

[github]
blob_re = "^Steam-ROM-Manager-portable.*\\.exe$"
user = "doZennn"
project = "steam-rom-manager"
