[info]
gist = "Video & audio player with broad support for file formats and network streams"
category = "Audio & Video"
name = "VLC media player"

[html]
versioning = "tuple"
blob_re = ".*<li><a href=\"(?P<url>//get\\.videolan\\.org/vlc/(?P<ver>.*?)/win64/vlc-.*?-win64\\.exe)\">Windows 64bit</a></li>.*"
url = "https://www.videolan.org/vlc/"

[local]
installer = "sfx"
delete = [
    "\\$PLUGINSDIR",
]
