name = "VLC media player"
url = "https://www.videolan.org/vlc/"
ver_scheme_type = "tuple"
blob_re = ".*<li><a href=\"(?P<url>//get\\.videolan\\.org/vlc/(?P<ver>.*?)/win64/vlc-.*?-win64\\.exe)\">Windows 64bit</a></li>.*"
blob_unwanted = [
    "\\$PLUGINSDIR",
]
installer = "sfx"
appdatas = []
repo = "html"

[info]
gist = "Video & audio player with broad support for file formats and network streams"
category = "Audio & Video"
