[info]
name = "VSCodium"
category = "Developer Tools"
gist = "Extensible code editor supporting many programming languages. This is VSCode without telemetry and Microsoft/GitHub account sync features."

[github]
blob_re = "^VSCodium-win32-x64-.*\\.zip$"
user = "VSCodium"
project = "vscodium"
