name = "VSCodium"
user = "VSCodium"
project = "vscodium"
blob_re = "^VSCodium-win32-x64-.*\\.zip$"
blob_unwanted = []
appdatas = []
repo = "github"

[info]
gist = "Extensible code editor supporting many programming languages. This is VSCode without telemetry and Microsoft/GitHub account sync features."
category = "Developer Tools"
