[info]
gist = "Extensible code editor supporting many programming languages"
category = "Developer Tools"
name = "VSCode"

[html]
versioning = "tuple"
ver_scheme_re = "\"(.*?)\""
url = "https://update.code.visualstudio.com/api/releases/stable"
blob_permalink = "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-archive"
