[info]
gist = "Emulates the Microsoft Xbox 360. Canary/experimental builds."
category = "Emulators"
name = "xenia-canary"

[github]
blob_re = "^xenia_canary\\.zip$"
user = "xenia-canary"
project = "xenia-canary"
