[info]
name = "XnView Classic"
category = "Audio & Video"
gist = "Image browser, viewer and converter"

[html]
url = "https://www.xnview.com/en/xnview/#downloads"
versioning = "tuple"
blob_permalink = "https://download.xnview.com/XnView-win-full.zip"
blob_permalink_re = "<p class=\"h5 mt-3\">Download <strong>XnView (.*?)</strong>.*?</p>"
