name = "XnView MP"
url = "https://www.xnview.com/en/xnviewmp/#downloads"
ver_scheme_type = "tuple"
ver_scheme_re = "<p class=\"h5 mt-3\">Download <strong>XnView MP (.*?)</strong>.*?</p>"
blob_permalink = "https://download.xnview.com/XnViewMP-win-x64.zip"
blob_unwanted = [
    "vc_redist\\.x64\\.exe",
]
appdatas = []
repo = "html"

[info]
gist = "Image browser, viewer and converter. More features than XnView Classic"
category = "Audio & Video"
