[info]
gist = "Image browser, viewer and converter"
category = "Audio & Video"
name = "XnView Classic"

[html]
versioning = "tuple"
ver_scheme_re = "<p class=\"h5 mt-3\">Download <strong>XnView (.*?)</strong>.*?</p>"
url = "https://www.xnview.com/en/xnview/#downloads"
blob_permalink = "https://download.xnview.com/XnView-win-full.zip"
