[info]
gist = "Image browser, viewer and converter. More features than XnView Classic"
category = "Audio & Video"
name = "XnView MP"

[html]
versioning = "tuple"
ver_scheme_re = "<p class=\"h5 mt-3\">Download <strong>XnView MP (.*?)</strong>.*?</p>"
url = "https://www.xnview.com/en/xnviewmp/#downloads"
blob_permalink = "https://download.xnview.com/XnViewMP-win-x64.zip"

[local]
delete = [
    "vc_redist\\.x64\\.exe",
]
