name = "XnView Classic"
url = "https://www.xnview.com/en/xnview/#downloads"
ver_scheme_type = "tuple"
ver_scheme_re = "<p class=\"h5 mt-3\">Download <strong>XnView (.*?)</strong>.*?</p>"
blob_permalink = "https://download.xnview.com/XnView-win-full.zip"
blob_unwanted = []
appdatas = []
repo = "html"

[info]
gist = "Image browser, viewer and converter"
category = "Audio & Video"
