[info]
name = "XnView MP"
category = "Audio & Video"
gist = "Image browser, viewer and converter. More features than XnView Classic"

[html]
url = "https://www.xnview.com/en/xnviewmp/#downloads"
versioning = "tuple"
blob_permalink = "https://download.xnview.com/XnViewMP-win-x64.zip"
blob_permalink_re = "<p class=\"h5 mt-3\">Download <strong>XnView MP (.*?)</strong>.*?</p>"

[local]
delete = [
    "vc_redist\\.x64\\.exe",
]
